version: "3.9"
services:
  mysql:
    image: mysql
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
    command: --innodb-use-native-aio=0
  goapp:
    image: goapp
    build: ./src
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app
