version: "3.9"
services:
  mysql:
    image: mysql
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - "./db/init:/docker-entrypoint-initdb.d"
    env_file:
      - "./db/envfile.txt"
    command: --innodb-use-native-aio=0
  goapp:
    image: goapp
    build: ./goapp
    stdin_open: true
    tty: true
    volumes:
      - ./goapp:/app
